In [5]:
import torch
import numpy as np

torch.manual_seed(0)

## Tensors

Torch tensors are PyTorch equivalent of numpy ndarrays. They share the same memory thus avoiding unnecessary copies. Unlike ndarrays, tensors can run on GPUs. They are also optimized for automatic differentiation.

In [6]:
# Direct initialization of tensors from inline data
tensor = torch.tensor([[1, 5], [.5, 6]])

print (tensor.shape)
print (tensor)

torch.Size([2, 2])
tensor([[1.0000, 5.0000],
        [0.5000, 6.0000]])


In [7]:
# From existing numpy ndarrays
arr = np.random.randint(100, size=(5, 2))
print ('Numpy Array', arr)
print (arr.shape)

tensor = torch.from_numpy(arr)
print ('Torch tensor', tensor)
print (tensor.shape)

Numpy Array [[ 4 52]
 [16 92]
 [67 45]
 [72 97]
 [ 0 72]]
(5, 2)
Torch tensor tensor([[ 4, 52],
        [16, 92],
        [67, 45],
        [72, 97],
        [ 0, 72]])
torch.Size([5, 2])


In [8]:
# A convenience method to build a tensor from the given tensor's shape

tensor = torch.tensor([[2, 3], [7, 9]])
print (torch.ones_like(tensor))
print (torch.rand_like(tensor, dtype=torch.float32))
print (torch.rand_like(tensor, dtype=torch.float16))
print (torch.rand_like(tensor, dtype=torch.bfloat16))

tensor([[1, 1],
        [1, 1]])
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])
tensor([[0.4077, 0.3726],
        [0.8452, 0.6753]], dtype=torch.float16)
tensor([[0.0352, 0.8242],
        [0.0820, 0.9453]], dtype=torch.bfloat16)


In [9]:
# Some useful functions to create tensors similar to numpy

print (torch.zeros(10))
print (torch.ones(10))
print (torch.rand(size=(5, 2), dtype=torch.bfloat16))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[0.1406, 0.3398],
        [0.2734, 0.8438],
        [0.3438, 0.5469],
        [0.2266, 0.7539],
        [0.8984, 0.1523]], dtype=torch.bfloat16)


In [10]:
tensor = torch.rand(size=(5, 2), dtype=torch.bfloat16)

print ('Shape', tensor.shape)
print ('Datatype', tensor.dtype)
print ('Device', tensor.device)

Shape torch.Size([5, 2])
Datatype torch.bfloat16
Device cpu


In [11]:
# Slicing and indexing
t = torch.rand(size=(5, 5))
print (t)

print ('t[0]', t[0])
print ('t[1, -1]', t[1, -1])
print ('t[:, -1]', t[:, -1])
print ('t[:, -1]', t[..., -1])

tensor([[0.1759, 0.2698, 0.1507, 0.0317, 0.2081],
        [0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155],
        [0.7932, 0.2783, 0.4820, 0.8198, 0.9971],
        [0.6984, 0.5675, 0.8352, 0.2056, 0.5932]])
t[0] tensor([0.1759, 0.2698, 0.1507, 0.0317, 0.2081])
t[1, -1] tensor(0.2437)
t[:, -1] tensor([0.2081, 0.2437, 0.8155, 0.9971, 0.5932])
t[:, -1] tensor([0.2081, 0.2437, 0.8155, 0.9971, 0.5932])


In [12]:
# Join tensors among dimensions
t = torch.rand(10)
print (torch.cat([t, t]))
print (torch.cat([t, t], axis=0))

t = torch.rand(size=(2, 5))
print (t)
print (torch.cat([t, t], axis=0)) # Axis = 0 will append to the base tensor
print (torch.cat([t, t], axis=1)) # Axis = 1 will append to L1 tensors

tensor([0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038, 0.6511, 0.7745, 0.4369,
        0.5191, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038, 0.6511, 0.7745,
        0.4369, 0.5191])
tensor([0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038, 0.6511, 0.7745, 0.4369,
        0.5191, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038, 0.6511, 0.7745,
        0.4369, 0.5191])
tensor([[0.6159, 0.8102, 0.9801, 0.1147, 0.3168],
        [0.6965, 0.9143, 0.9351, 0.9412, 0.5995]])
tensor([[0.6159, 0.8102, 0.9801, 0.1147, 0.3168],
        [0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.6159, 0.8102, 0.9801, 0.1147, 0.3168],
        [0.6965, 0.9143, 0.9351, 0.9412, 0.5995]])
tensor([[0.6159, 0.8102, 0.9801, 0.1147, 0.3168, 0.6159, 0.8102, 0.9801, 0.1147,
         0.3168],
        [0.6965, 0.9143, 0.9351, 0.9412, 0.5995, 0.6965, 0.9143, 0.9351, 0.9412,
         0.5995]])


## Automatic Differentiation

In [13]:
a = torch.tensor([2., 3], requires_grad=True, dtype=torch.float32)
b = torch.tensor([5., 8], requires_grad=True, dtype=torch.float32)

Q = 3 * a**3 + 1.5 * b
Q.sum().backward()

In [14]:
assert torch.all(a.grad == 9 * a**2)
assert torch.all(b.grad == torch.tensor([1.5, 1.5]))

## CUDA

In [24]:
print (f'Is a CUDA device available? {torch.cuda.is_available()}')
print (f'How many CUDA devices? {torch.cuda.device_count()}')
print (f'Which device? {torch.cuda.get_device_name(0)}')

Is a CUDA device available? True
How many CUDA devices? 1
Which device? NVIDIA GeForce RTX 4080


In [30]:
# Sending a tensor to the CUDA device

tensor = torch.tensor([.1, .65], dtype=torch.float32).to('cuda')
add = torch.tensor([.5, .5]).to('cuda')

tensor + add

tensor([0.6000, 1.1500], device='cuda:0')

In [35]:
mat1 = torch.tensor([[1, 65], [3, 5]], dtype=torch.float32).to('cuda')
mat2 = torch.tensor([[10, 6], [30, 5]], dtype=torch.float32).to('cuda')

mat1 @ mat2

tensor([[1960.,  331.],
        [ 180.,   43.]], device='cuda:0')

In [36]:
mat1 @ mat2.T

tensor([[400., 355.],
        [ 60., 115.]], device='cuda:0')